In [13]:
import matplotlib.pyplot as plt
from matplotlib import rc
import numpy as np
from scipy.optimize import curve_fit
from uncertainties import ufloat
from uncertainties import unumpy as unp
import csv
import pandas as pd
import sympy as sym
import fprlib as fp

rc('font', **{'family': 'serif', 'serif': ['Computer Modern']}) #font na grafih je LaTexov
rc('text', usetex=True)

In [29]:
t_1_neprocesirano = np.array([22.25, 22.01, 22.17])
t_kocka_neprocesirano = np.array([42.76, 42.81, 42.77])
t_valj_neprocesirano = np.array([62.09, 61.89, 61.86])
t_zobnik_neprocesirano = np.array([34.66, 34.71, 34.66])

t_prazno_single = t_1_neprocesirano /10
t_kocka_single = t_kocka_neprocesirano /10
t_valj_single = t_valj_neprocesirano /10
t_zobnik_single= t_zobnik_neprocesirano /10

print(t_prazno_single)
print(t_kocka_single)
print(t_valj_single)
print(t_zobnik_single)


m_kocka = ufloat(1.193, 0.002)
m_valj = ufloat(2.488, 0.002)
m_zobnik = ufloat(0.755, 0.002)

a_kocke = ufloat(0.0600, 0.0015)
d_kocka_luknje = ufloat(0.0400, 0.0015)

h_valj = ufloat(0.0494, 0.0015)
d_valj_notranja = ufloat(0.0145, 0.0015)
d_valja_zunanja = ufloat(0.0879, 0.0030)

print("")
print(np.average(t_prazno_single), np.std(t_prazno_single))
print(np.average(t_kocka_single), np.std(t_kocka_single))
print(np.average(t_valj_single), np.std(t_valj_single))
print(np.average(t_zobnik_single), np.std(t_zobnik_single))




[2.225 2.201 2.217]
[4.276 4.281 4.277]
[6.209 6.189 6.186]
[3.466 3.471 3.466]

2.2143333333333337 0.009977753031397186
4.278 0.002160246899469597
6.1946666666666665 0.01020892855407595
3.4676666666666662 0.0023570226039553175


In [31]:

J_v_izr = 0
J_k_izr = 0

J_v_izm = 0
J_k_izm = 0

D = 0

J_z = 0
G = 0

NameError: name 'J_v' is not defined

In [147]:
# valj

r_1 = d_valj_notranja / 2
r_2 = d_valja_zunanja / 2
m = m_valj

J_v_izr = 0.5*m* (r_1**2 + r_2**2)
print(J_v_izr*1000)

2.47+/-0.16


In [149]:
# Kvader izračunano

a = a_kocke
d = d_kocka_luknje
m = m_kocka

J_k_izr = m/24 * ((16*a**4-3*d**4)/(4*a**2-np.pi*d**2))
print(J_k_izr*1000)

1.06+/-0.05


In [121]:
# Torzijski koeficient D

J_v = 0.5*m_valj* ((d_valj_notranja/2)**2 + (d_valja_zunanja / 2)**2)
t_p = ufloat(np.average(t_prazno_single), np.std(t_prazno_single))
t_v = ufloat(np.average(t_valj_single), np.std(t_valj_single))

# D = (2*np.pi*J_v/t_v)/(1-(t_p/t_v)**2)
D = (4*J_v*np.pi**2)/(t_v**2 - t_p**2)

print(D*1000) 

2.91+/-0.19


In [111]:
# Izračun J_k po meritvah

D1 = D
t_v = ufloat(np.average(t_valj_single), np.std(t_valj_single))
t_k = ufloat(np.average(t_kocka_single), np.std(t_kocka_single))

J_k_mer = D * (t_k**2 - t_p**2) /(4*np.pi**2)

print(J_k_mer*1000)#gramov meter^2

0.99+/-0.07


In [115]:
# Izračun J_z po meritvah

D1 = D
t_v = ufloat(np.average(t_valj_single), np.std(t_valj_single))
t_z = ufloat(np.average(t_zobnik_single), np.std(t_zobnik_single))

J_z_mer = D1 * (t_z**2 - t_p**2) /(4*np.pi**2)

print(J_z_mer*1000)#gramov meter^2

0.525+/-0.035


In [145]:
# Izračun strižnega modula

r_0 = ufloat(0.0006, 0.00005)
D1 = D
l = ufloat(0.29, 0.005)

G = (D*2*l)/(np.pi*r_0**4)

print(G/1000000000)

4.1+/-1.4
